//
// Generated file, do not edit! Created by opp_msgc 4.3 from networklayer/manetrouting/VCap/msgReq.msg.
//

#ifndef _MSGREQ_M_H_
#define _MSGREQ_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "IPv4Address.h"
// }}



/**
 * Class generated from <tt>networklayer/manetrouting/VCap/msgReq.msg</tt> by opp_msgc.
 * <pre>
 * packet msgReq {
 *    IPv4Address srcIP;
 *   
 *    IPv4Address  destIP;
 *   
 *   
 * 
 *    
 *   
 *     
 * };
 * </pre>
 */
class INET_API msgReq : public ::cPacket
{
  protected:
    IPv4Address srcIP_var;
    IPv4Address destIP_var;

  private:
    void copy(const msgReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const msgReq&);

  public:
    msgReq(const char *name=NULL, int kind=0);
    msgReq(const msgReq& other);
    virtual ~msgReq();
    msgReq& operator=(const msgReq& other);
    virtual msgReq *dup() const {return new msgReq(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPv4Address& getSrcIP();
    virtual const IPv4Address& getSrcIP() const {return const_cast<msgReq*>(this)->getSrcIP();}
    virtual void setSrcIP(const IPv4Address& srcIP);
    virtual IPv4Address& getDestIP();
    virtual const IPv4Address& getDestIP() const {return const_cast<msgReq*>(this)->getDestIP();}
    virtual void setDestIP(const IPv4Address& destIP);
};

inline void doPacking(cCommBuffer *b, msgReq& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, msgReq& obj) {obj.parsimUnpack(b);}


#endif // _MSGREQ_M_H_
