//
// Generated file, do not edit! Created by opp_msgc 4.3 from networklayer/manetrouting/VCap/msgW.msg.
//

#ifndef _MSGW_M_H_
#define _MSGW_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "IPv4Address.h"
#include <vector>
typedef std::vector<IPv4Address> pathTable;
#define PHASE_NULL 0
#define PHASE_W 1
#define PHASE_X 2
#define PHASE_Y 3
#define PHASE_Z 4
#define PHASE_X1 5
#define PHASE_X2 6
// }}



/**
 * Class generated from <tt>networklayer/manetrouting/VCap/msgW.msg</tt> by opp_msgc.
 * <pre>
 * packet msgW {
 *    int phase=PHASE_NULL; 
 *    pathTable path;
 *    IPv4Address srcIP;
 *    double srcW; 
 *    double srcX;
 * 
 *    double hop=0;
 * 
 *    
 *   
 *     
 * };
 * </pre>
 */
class INET_API msgW : public ::cPacket
{
  protected:
    int phase_var;
    pathTable path_var;
    IPv4Address srcIP_var;
    double srcW_var;
    double srcX_var;
    double hop_var;

  private:
    void copy(const msgW& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const msgW&);

  public:
    msgW(const char *name=NULL, int kind=0);
    msgW(const msgW& other);
    virtual ~msgW();
    msgW& operator=(const msgW& other);
    virtual msgW *dup() const {return new msgW(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPhase() const;
    virtual void setPhase(int phase);
    virtual pathTable& getPath();
    virtual const pathTable& getPath() const {return const_cast<msgW*>(this)->getPath();}
    virtual void setPath(const pathTable& path);
    virtual IPv4Address& getSrcIP();
    virtual const IPv4Address& getSrcIP() const {return const_cast<msgW*>(this)->getSrcIP();}
    virtual void setSrcIP(const IPv4Address& srcIP);
    virtual double getSrcW() const;
    virtual void setSrcW(double srcW);
    virtual double getSrcX() const;
    virtual void setSrcX(double srcX);
    virtual double getHop() const;
    virtual void setHop(double hop);
};

inline void doPacking(cCommBuffer *b, msgW& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, msgW& obj) {obj.parsimUnpack(b);}


#endif // _MSGW_M_H_
