#define PU_CHA// the channel will be influenced by PUs, don't comment this one
#define PU_ON // PUs operate during transmission, they are off if they are commented
//#define MULTI_CHA
#define CAVCAP// the VC is generated by cavcap
#define CAVCAPBUFFER
#define DTM //duty cycle
//#define EWT // delay
//#define SEARCH_ROUTING
//#define ONLY_USE_CHANNEL_0
#define MORE_AHCHOR_6 // 6 anchors
#define BUFFER_WHEN_NEIGHBOUR_IS_ON //when sender's channel is OFF, but neighbors' channel is ON, buffer!
//#define ACCURATE_DELAY // comment a line in ChannelAccess.cc, about setTimestamp()
#define UNIFORMED_CHECKBUFFER_INTERVAL
