//
// Generated file, do not edit! Created by opp_msgc 4.3 from networklayer/manetrouting/GPS/msgNeighbor.msg.
//

#ifndef _MSGNEIGHBOR_M_H_
#define _MSGNEIGHBOR_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "IPv4Address.h"
// }}



/**
 * Class generated from <tt>networklayer/manetrouting/GPS/msgNeighbor.msg</tt> by opp_msgc.
 * <pre>
 * packet msgNeighbor {
 *     IPv4Address srcIP;
 *     
 *     int X;
 *     int Y;
 *    
 *     int hop1_2=1;
 * };
 * </pre>
 */
class INET_API msgNeighbor : public ::cPacket
{
  protected:
    IPv4Address srcIP_var;
    int X_var;
    int Y_var;
    int hop1_2_var;

  private:
    void copy(const msgNeighbor& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const msgNeighbor&);

  public:
    msgNeighbor(const char *name=NULL, int kind=0);
    msgNeighbor(const msgNeighbor& other);
    virtual ~msgNeighbor();
    msgNeighbor& operator=(const msgNeighbor& other);
    virtual msgNeighbor *dup() const {return new msgNeighbor(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPv4Address& getSrcIP();
    virtual const IPv4Address& getSrcIP() const {return const_cast<msgNeighbor*>(this)->getSrcIP();}
    virtual void setSrcIP(const IPv4Address& srcIP);
    virtual int getX() const;
    virtual void setX(int X);
    virtual int getY() const;
    virtual void setY(int Y);
    virtual int getHop1_2() const;
    virtual void setHop1_2(int hop1_2);
};

inline void doPacking(cCommBuffer *b, msgNeighbor& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, msgNeighbor& obj) {obj.parsimUnpack(b);}


#endif // _MSGNEIGHBOR_M_H_
