//
// Generated file, do not edit! Created by opp_msgc 4.3 from networklayer/manetrouting/search/searNeighborInfo.msg.
//

#ifndef _SEARNEIGHBORINFO_M_H_
#define _SEARNEIGHBORINFO_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "IPv4Address.h"
// }}



/**
 * Class generated from <tt>networklayer/manetrouting/search/searNeighborInfo.msg</tt> by opp_msgc.
 * <pre>
 * packet searNeighborInfo
 * {
 * 	IPv4Address routerAddress;
 * 	double routerXPos;
 * 	double routerYPos;
 * 	bool workingChannel; 
 * 
 * 	int dist2Dst;
 * }
 * </pre>
 */
class INET_API searNeighborInfo : public ::cPacket
{
  protected:
    IPv4Address routerAddress_var;
    double routerXPos_var;
    double routerYPos_var;
    bool workingChannel_var;
    int dist2Dst_var;

  private:
    void copy(const searNeighborInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const searNeighborInfo&);

  public:
    searNeighborInfo(const char *name=NULL, int kind=0);
    searNeighborInfo(const searNeighborInfo& other);
    virtual ~searNeighborInfo();
    searNeighborInfo& operator=(const searNeighborInfo& other);
    virtual searNeighborInfo *dup() const {return new searNeighborInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPv4Address& getRouterAddress();
    virtual const IPv4Address& getRouterAddress() const {return const_cast<searNeighborInfo*>(this)->getRouterAddress();}
    virtual void setRouterAddress(const IPv4Address& routerAddress);
    virtual double getRouterXPos() const;
    virtual void setRouterXPos(double routerXPos);
    virtual double getRouterYPos() const;
    virtual void setRouterYPos(double routerYPos);
    virtual bool getWorkingChannel() const;
    virtual void setWorkingChannel(bool workingChannel);
    virtual int getDist2Dst() const;
    virtual void setDist2Dst(int dist2Dst);
};

inline void doPacking(cCommBuffer *b, searNeighborInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, searNeighborInfo& obj) {obj.parsimUnpack(b);}


#endif // _SEARNEIGHBORINFO_M_H_
