//
// Generated file, do not edit! Created by opp_msgc 4.3 from networklayer/manetrouting/dymo_fau/DYMO_RREQ.msg.
//

#ifndef _DYMO_RREQ_M_H_
#define _DYMO_RREQ_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "DYMO_RM_m.h"
// }}



/**
 * Class generated from <tt>networklayer/manetrouting/dymo_fau/DYMO_RREQ.msg</tt> by opp_msgc.
 * <pre>
 * message DYMO_RREQ extends DYMO_RM
 * {
 * }
 * </pre>
 */
class INET_API DYMO_RREQ : public ::DYMO_RM
{
  protected:

  private:
    void copy(const DYMO_RREQ& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DYMO_RREQ&);

  public:
    DYMO_RREQ(const char *name=NULL, int kind=0);
    DYMO_RREQ(const DYMO_RREQ& other);
    virtual ~DYMO_RREQ();
    DYMO_RREQ& operator=(const DYMO_RREQ& other);
    virtual DYMO_RREQ *dup() const {return new DYMO_RREQ(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, DYMO_RREQ& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DYMO_RREQ& obj) {obj.parsimUnpack(b);}


#endif // _DYMO_RREQ_M_H_
