//
// Generated file, do not edit! Created by opp_msgc 4.3 from applications/tcpapp/GenericAppMsg.msg.
//

#ifndef _GENERICAPPMSG_M_H_
#define _GENERICAPPMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Class generated from <tt>applications/tcpapp/GenericAppMsg.msg</tt> by opp_msgc.
 * <pre>
 * packet GenericAppMsg
 * {
 *     int expectedReplyLength; 
 *     double replyDelay;       
 *     bool serverClose;        
 *                              
 * }
 * </pre>
 */
class INET_API GenericAppMsg : public ::cPacket
{
  protected:
    int expectedReplyLength_var;
    double replyDelay_var;
    bool serverClose_var;

  private:
    void copy(const GenericAppMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GenericAppMsg&);

  public:
    GenericAppMsg(const char *name=NULL, int kind=0);
    GenericAppMsg(const GenericAppMsg& other);
    virtual ~GenericAppMsg();
    GenericAppMsg& operator=(const GenericAppMsg& other);
    virtual GenericAppMsg *dup() const {return new GenericAppMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getExpectedReplyLength() const;
    virtual void setExpectedReplyLength(int expectedReplyLength);
    virtual double getReplyDelay() const;
    virtual void setReplyDelay(double replyDelay);
    virtual bool getServerClose() const;
    virtual void setServerClose(bool serverClose);
};

inline void doPacking(cCommBuffer *b, GenericAppMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GenericAppMsg& obj) {obj.parsimUnpack(b);}


#endif // _GENERICAPPMSG_M_H_
